version: '2' 
services:

  keys_server:
    image: coreoasis/piwind_keys_server:${RELEASE_TAG}
    restart: always
    container_name: piwind_keys_server
    ports:
     - 9003:80

  execution_worker:
    image: coreoasis/model_execution_worker:${RELEASE_TAG}
    restart: always
    container_name: piwind_worker
    volumes:
     - ${HOME}/OasisPiWind/model_data/PiWind/:/var/oasis/model_data/OasisLMF/PiWind
     - ${WORKER_UPLOAD_PATH}:/var/www/oasis/upload:rw
     - ${WORKER_DOWNLOAD_PATH}:/var/www/oasis/download:rw
     - /tmp:/tmp
    # Prevent the machine craching due to excessive memory pressure
    mem_limit: 50g
    # Vulnerability data is loaded in shm
    shm_size: 15g
    # Required to allow GDB
    privileged: true
    environment:
     - MODEL_SUPPLIER_ID=OasisLMF
     - MODEL_VERSION_ID=PiWind
     - LOCK_FILE = '/tmp/tmp_ktools_lock_file'
     - DO_CLEAR_WORKING = True
     - KTOOLS_BATCH_COUNT=-1
     - RABBIT_PORT=${API_RABBIT_PORT}
     - MYSQL_PORT=${API_MYSQL_PORT}
    links:
     - oasis_mysql:mysql
     - oasis_rabbit:rabbit
